### ISSUE TITLE
page for all public members

### ISSUE THREAD

**Issue by fabiantheblind** [FH-Potsdam/fh-potsdam.github.com#6]
you can get the avatars from the github API

**Comment by fabiantheblind** [comment]
{% for student in site.data.wise-1415.students %}
        <div class="media people well" id="{{ student.github }}">
            <a href="{{ student.url }}" class="media-left">
                <img alt=" " src="https://avatars.githubusercontent.com/{{ student.github }}" class="hidden-xs avatars-large">
                <img alt=" " src="https://avatars.githubusercontent.com/{{ student.github }}" class="thumb hidden-sm hidden-md hidden-lg avatars-small">
            </a>
            <div class="media-body break">
                <p>Hi my name is</p>
                <h4 class="media-heading headline">{{ student.author }}</h4>
                <h5>or <a href="https://github.com/{{ student.github }}">{{ student.github }}</a> on GitHub</h5>
                <div class="hidden-xs">
                {% include person.html %}
                </div>
            </div>
                <div class="hidden-sm hidden-md hidden-lg">
                {% include person.html %}
                </div>
        </div>
    {% endfor %}

**Comment by paulvollmer** [comment]
http://fh-potsdam.github.io/members

**Comment by fabiantheblind** [comment]
Cool. :+1:

**Comment by paulvollmer** [comment]
we need a design for this page

**Comment by fabiantheblind** [comment]
I think we should collapse the rows on mobile. Looks very small
