### ISSUE TITLE
Add meta-data to every repo to allow better filtering

### ISSUE THREAD

**Issue by timpulver** [FH-Potsdam/fh-potsdam.github.com#7]
We should add a Json-file to every repository with some basic infos. This would allow us to implement better filtering and show some basic infos on the repo-overview-page.
It could look like:

```
{
  "repo_type": "project" / "course-material" / "framework / tool / app" / "tutorial / example"
}
```

Explanation of the above:

**project**:
Source-code of a project, this may not be documented and will often be used as a private repository without the intend to share with the outer world.

**tutorial / example**
A repository to help others understand a certain topic, a learning resource.

**course-material**:
E.g. [Eingabe-Ausgabe](https://github.com/FH-Potsdam/eingabe-ausgabe)

**framweork / tool**:
E.g. [ol3-dem](https://github.com/FH-Potsdam/ol3-dem)
Something with a specific purpose, to use right away, this should have example-code as well, an open source project.

For most people from outside the real oben source projects and tutorials / examples will be the most interesting repos.

There is probably a lot more meta-data which makes sense to specify.

To make it easier for people to include this file, there could be a simple website to generate the Json.

**Comment by paulvollmer** [comment]
good idea but we want to generate the website from data comming from the github api and without additional effort...

**Comment by timpulver** [comment]
Maybe some infos can be put in the repo-description in a structured way then!?
I think most of the repos are uninteresting for non-FHP-people, so it would be good to make the interesting ones more visible.

**Comment by fabiantheblind** [comment]
Getting members to add additional data is pretty hard. I also would stick with the data the github api provides for now

**Comment by fabiantheblind** [comment]
I'll close this issue. GitHub is constantly improving the gh-pages engine. We should not force structure into the projects.
